# Generated by Django 2.2.7 on 2021-01-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateName', models.CharField(max_length=50, verbose_name='cate_name')),
                ('bordref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cateref', to='board.Board')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
    ]
