# Generated by Django 2.2.7 on 2021-01-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50, verbose_name='task_title')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('cateref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskref', to='categorie.Categories')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
